### ISSUE TITLE
Add Clock.gif to README.md

### ISSUE THREAD

**Issue by nishantnahata** [nishantcoder97/react-clock#1]

**Comment by fllprbt** [comment]
Can I have it?

**Comment by johnnybigoode-zz** [comment]
If this is available, I'd like to take it.

**Comment by chosenvictim** [comment]
Created a pull request
https://github.com/nishantcoder97/react-clock/pull/2

**Comment by johnnybigoode-zz** [comment]
Woops, haven't seen that I was too slow. 
@chosenvictim hosting the image in a third party website is not a good practice. 
@deshazerj  you shouldn't reference your own repository to show an image. I do recommend reading: https://stackoverflow.com/questions/14494747/add-images-to-readme-md-on-github

**Comment by deshazerj** [comment]
I tried using relative paths first and GitHub wouldn't display the image. I must have done something wrong. Thanks for the advice. I'd be happy to update my PR if you'd like.
